### ISSUE TITLE
ModuleNotFoundError: No module named '_tkinter'

### ISSUE THREAD

**Issue by jeanccoelho** [PURPYL-MEDIA/btc-hack#33]
imac@computador btc-hack % python3 btc-hack-v2.py
Traceback (most recent call last):
  File "/Users/imac/Desktop/btc-hack/btc-hack-v2.py", line 16, in <module>
    import PySimpleGUI as sg
  File "/usr/local/lib/python3.9/site-packages/PySimpleGUI/__init__.py", line 2, in <module>
    from .PySimpleGUI import *
  File "/usr/local/lib/python3.9/site-packages/PySimpleGUI/PySimpleGUI.py", line 128, in <module>
    import tkinter as tk
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

**Comment by jrmessiah** [comment]
https://stackoverflow.com/questions/25905540/importerror-no-module-named-tkinter

**Comment by fobabs** [comment]
Just run `pip install PySimpleGUI`
